function shuffleArray(arr){ const a=arr.slice(); for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]} return a; }
let discs=[], targetNumber=1, isFlipping=false, gameStatus='playing', showRules=true;
function setMessage(msg){ const el=document.getElementById('msg'); if(el) el.textContent=msg; }
function triggerConfetti(){ const duration=3000, end=Date.now()+duration; (function frame(){ if(window.confetti){ window.confetti({ particleCount:5, angle:60, spread:55, origin:{x:0}, colors:['#d4a373','#eab308','#ffffff'] }); window.confetti({ particleCount:5, angle:120, spread:55, origin:{x:1}, colors:['#d4a373','#eab308','#ffffff'] }); } if(Date.now()<end) requestAnimationFrame(frame); })(); }
function render(){ const root=document.getElementById('app')||document.getElementById('root'); if(!root) return; root.innerHTML=`
  <div class="min-h-screen flex flex-col items-center justify-center p-4 select-none">
    <div class="text-center mb-8 z-10">
      <h1 class="text-4xl font-bold text-gray-800 mb-2">Memoria de Madera</h1>
      <p id="msg" class="text-xl text-gray-600 font-medium h-8 transition-all duration-300"></p>
    </div>
    <div class="relative bg-white rounded-3xl shadow-xl p-4 md:p-8 w-full max-w-2xl border-4 border-gray-100">
      <button id="btn-restart" class="absolute top-4 right-4 text-gray-400 hover:text-gray-600 transition-colors" title="Reiniciar Juego">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/><path d="M3 3v5h5"/><path d="M3 12a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16"/><path d="M16 16h5v5"/></svg>
      </button>
      <div id="grid" class="flex flex-wrap justify-center gap-4 md:gap-6 py-4"></div>
    </div>
    <div class="mt-8 text-gray-500 text-sm text-center max-w-md">El juego se reinicia automáticamente si le das al botón de recarga.<br/>¡Intenta memorizar las posiciones cuando te equivoques!</div>
    <div id="win-overlay" class="hidden fixed inset-0 z-50 flex items-center justify-center bg-black/20 backdrop-blur-sm"><div class="bg-white p-8 rounded-2xl shadow-2xl text-center"><h2 class="text-5xl mb-4">🏆</h2><h3 class="text-3xl font-bold text-gray-800 mb-2">¡Excelente!</h3><p class="text-gray-600 mb-6">Has completado la secuencia perfecta.</p><button id="btn-play-again" class="bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-3 px-8 rounded-full shadow-lg transition-transform">Jugar de Nuevo</button></div></div>
  </div>`;
  document.getElementById('btn-restart')?.addEventListener('click', initGame);
  document.getElementById('btn-play-again')?.addEventListener('click', initGame);
  const grid=document.getElementById('grid'); discs.forEach(d=>{ const slot=document.createElement('div'); slot.className='relative w-20 h-20 md:w-24 md:h-24'; const ring=document.createElement('div'); ring.className='absolute inset-0 rounded-full table-ring box-border opacity-20 pointer-events-none bg-gray-50 transform scale-110'; slot.appendChild(ring); const wrap=document.createElement('div'); wrap.className='w-full h-full perspective-1000 cursor-pointer group'; slot.appendChild(wrap); const card=document.createElement('div'); card.className='relative w-full h-full transition-transform duration-500 transform-style-3d'; wrap.appendChild(card); const front=document.createElement('div'); front.className='absolute w-full h-full backface-hidden'; const frontInner=document.createElement('div'); frontInner.className='w-full h-full rounded-full wood-texture wood-grain shadow-lg flex items-center justify-center group-hover:scale-105 transition-transform'; front.appendChild(frontInner); const fd=document.createElement('div'); fd.className='w-16 h-16 rounded-full border border-yellow-900/10 opacity-50'; frontInner.appendChild(fd); card.appendChild(front); const back=document.createElement('div'); back.className='absolute w-full h-full backface-hidden rotate-y-180'; const backInner=document.createElement('div'); backInner.className=`w-full h-full rounded-full border-4 ${d.isRevealed ? 'bg-green-50 border-green-600' : 'bg-white border-gray-800'} shadow-inner flex items-center justify-center`; const num=document.createElement('span'); num.className=`text-4xl font-bold ${d.isRevealed ? 'text-green-700' : 'text-gray-900'}`; num.textContent=String(d.number); backInner.appendChild(num); back.appendChild(backInner); card.appendChild(back); function refresh(){ card.classList.toggle('rotate-y-180', d.isRevealed || d.isTempRevealed); backInner.className=`w-full h-full rounded-full border-4 ${d.isRevealed ? 'bg-green-50 border-green-600' : 'bg-white border-gray-800'} shadow-inner flex items-center justify-center`; num.className=`text-4xl font-bold ${d.isRevealed ? 'text-green-700' : 'text-gray-900'}`; }
    wrap.addEventListener('click', ()=> handleDiscClick(d, refresh)); grid.appendChild(slot); }); setMessage(gameStatus==='won' ? '¡Ganaste! 🎉' : `Busca el ${targetNumber}`);
}
function initGame(){ const numbers=Array.from({length:10},(_,i)=>i+1); discs=shuffleArray(numbers).map((n,i)=>({id:i,number:n,isRevealed:false,isTempRevealed:false})); targetNumber=1; isFlipping=false; gameStatus='playing'; setMessage('Encuentra el 1'); render(); }
function handleDiscClick(clickedDisc, refresh){ if(isFlipping || clickedDisc.isRevealed || gameStatus==='won') return; if(clickedDisc.number===targetNumber){ clickedDisc.isRevealed=true; refresh(); const next=targetNumber+1; if(next>10){ gameStatus='won'; setMessage('¡Ganaste! 🎉'); triggerConfetti(); const ov=document.getElementById('win-overlay'); if(ov) ov.classList.remove('hidden'); } else { targetNumber=next; setMessage(`¡Bien! Ahora encuentra el ${next}`); } } else { isFlipping=true; setMessage(`¡Ups! Ese es el ${clickedDisc.number}`); clickedDisc.isTempRevealed=true; refresh(); setTimeout(()=>{ clickedDisc.isTempRevealed=false; refresh(); isFlipping=false; setMessage(`Busca el ${targetNumber}`); },1000); } }
document.addEventListener('DOMContentLoaded', initGame);
